### ISSUE TITLE
Editing player

### ISSUE THREAD

**Issue by Generalmino08** [xAranaktu/FIFA-21-CM-Cheat-Table#4]
Firstly love your work!

I have an issue when i edit players i CM. I edit them allright, but the stats only last one game then they go back to the stats they had before. Maybe i'm just missing something i'm not sure. I'm doing the same way as i did in FIFA 20 and the stats stil reset after i played one game. What's the issue?

**Comment by xAranaktu** [comment]
1. If you have downloaded latest game update (title update 4) then you need cheat table v21.1.0.8 or newer. Older version won't work.
2. You need to edit player through GUI because of the new player growth system. Editing database table only won't work.
3. If you play player career mode you need to enter "[Edit Pro](https://github.com/xAranaktu/FIFA-21-CM-Cheat-Table/wiki/Editing-Player#editing-player-in-player-career-mode)" after you have done editing the player to save the changes permanently.
